version: "3.5"
services: 
  postgres-compose: 
    image: postgres
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desafio-everyminds
    ports: 
      - "5432:5432"
    volumes: 
      - ./data:/var/lib/postgresql/data

volumes:
  data: